dist: trusty
sudo: required

language: c
compiler:
    - gcc
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   # - secure: "NQfOgGEF006EmuHJnFY+SLLrQQ3UJHDLY07JPx1iuIIb7cvo/2kWQB0JI3VeZWzgRH2Var3GknKI0Z4bbogDTIeOhDX3HpXzGOtp4VcIvIKHuReUW1Oq5MDVP9ZK5FByxGgm1NjQKC4jrYBJRfj9SM9jGOE2ErYBqmACcRBNHVCtRoCDBiaigoRWjTVXE16yx/nKoPPm49k/QuVHT/c4IlQtqkIiXKqO+S84fXIQLtCfuqqJW8nJMDXnvb+Ze6EIuhy2t386Kf94Vlx3OvTNQGYNz4ESkuwJCxfmeQzmarEyCfFjX91L1Bm1u61aqIftjxpr154XuYYxSEC5oZuCSd1y5Ugu7K9jWUMrMtS4iPzoWBGrnJTdRX/jWmqdi+HQLCDiZSOg2RI47TRN9D1yYVMxdIiewMcS5HGojNQWqETgJZ0ovmPwiaDt0Hgp4iLdsMv1hPOKyTT1JhY7cWYWiBMa+vYKWg0JT2mELCVwCcMBwATxQZ72XlA2KeMAFVbhfhG4wNTnVlTkFlWMEYzM9of7UnM5TrXPyALBA3wUiy36gPibAwl0O5cYPOV1UfMcnW8lbLTNh7DhZOuEKWhbNIFPq/1h0Fh9fJ2/KdEJWBfMC+CmAC0HvvhfN1d5c9Vsi9SvWChym6sUW2Qwjr/3TQNOJEbbJixnorehXFL99PY="

addons:
  coverity_scan:
    project:
      name: "Comcast/parodus2ccsp"
      description: " Webpa client to communicate with parodus in RDK environment. "
    notification_email: weston_schmidt@alumni.purdue.edu
    build_command_prepend: "mkdir coverity_build && cd coverity_build && cmake .."
    build_command:   "make"
    branch_pattern: coverity_scan

before_install:
    - sudo pip install codecov

install:
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq libcunit1 libcunit1-dev lcov libcurl4-openssl-dev
    - sudo add-apt-repository -y ppa:0k53d-karl-f830m/openssl
    - sudo apt-get update
    # Fedora equivalent is expat-devel
    - sudo apt-get -y install openssl libexpat1-dev
    - openssl version -a

script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TESTING:BOOL=true
    - sudo make
    - make test

after_success:
    - codecov
